### ISSUE TITLE
Union Depository Bank Heist

### ISSUE THREAD

**Issue by FusionzZKnight** [Irovolve/Haven#19]
**Is your feature request related to a problem? Please describe.**
[A clear and concise description of what the problem is. **Remove this line!**]

**Describe the feature you'd like**
[A clear and concise description of what you want to happen. Include any documents, mock-ups or anything else related to implementing your idea if possible. **Remove this line!**]

**Describe alternatives you've considered**
[A clear and concise description of any alternative solutions or features you've considered. **Remove this line!**]

**Additional context**
[Add any other context or screenshots about the feature request here. **Remove this line!**]

**Comment by xavlios** [comment]
no description. so closing. however new heist is coming
