### ISSUE TITLE
Police cars too slow compared to others... : ( 

### ISSUE THREAD

**Issue by Geckoooo** [Irovolve/Haven#23]
**Describe the current reason for this balance request**
Cop cars can barely keep up, we lose some people on straightaways ......

**Describe the solution you'd like**
Balancing other cars or tuning the cop cars.

**Additional context**
N/A

**Comment by EbonTheChamp** [comment]
What cars are out-running cruisers, vehicles with mechanic upgrades? When I had the chance to drive a cruiser it seemed like it was 212 mph on rails. /Shrug
Cars straight off the lot haven't seemed one-sided on the few chases I've been in. So maybe tune ups are over tuned? End of the day, there needs to be skill involved from both parties, and nerfing/overturning vehicles base stats might not be the best solution.

Just some thoughts, do with them what you will.

Take it easy Vato
