### ISSUE TITLE
Appellate Court Channel

### ISSUE THREAD

**Issue by Mizund** [Irovolve/Haven#6]
**Is your feature request related to a problem? Please describe.**
Yes my feature is related to a problem that I had. When I got arrested I was to be fined 300K without an attorney. I requested to contact someone to be my attorney, so that some of the charges would've been dropped and I would've had a less hefty fine to pay off. So my idea that I have come up with would help with situations where the police fail to do their jobs correctly. (They did their jobs correctly. up to the point until they denied an attorney. Maybe next time they should read the constitution.)

**Describe the feature you'd like**
I would like a channel in the discord called the Appellate Court. If you don't know what an appellate court is. Let me explain. An appellate court is a court that is higher than the district court. The district court will rule a verdict charging someone or even sentencing someone to time for a crime. If that person who was fined or sentenced believes that their case was misinterpreted or was not judged correctly. Then they can opt for an appeal. Then the appellate court would go over the case in which that person was charged in to see if it was done incorrectly. In my case I was completely denied an attorney, so the appellate court would see that my trial was unfair, and they would either appeal the charges or offer me a fair retrial.

**Describe alternatives you've considered**
Well to be honest. what I explained above would make the server more realistic, so unless you want people complaining to the owner about their charges. Then the appellate court channel would be very helpful.

**Additional context**
none.

**Comment by Irovolve** [comment]
Attorneys are becoming a WL job soon, and if there are no attorneys in the city, guess what! We aren't required to give you one. We are only required to give you a Lawyer if there is a licensed lawyer on. Let me also state that you did every single one of your crimes right in front of 3 officers, even after we told you to stop. A lawyer can't help you there even if you did get one bud.
