### ISSUE TITLE
Pilots License

### ISSUE THREAD

**Issue by Mizund** [Irovolve/Haven#7]
**Is your feature request related to a problem? Please describe.**
Yesterday I was arrested after flying a plane "illegally" without question of my knowledge of how to follow airport procedures for passenger aircrafts and Dreamliners. So if you didn't know I have a ton of knowledge of how airtraffic works. I used to play tons of multiplayer infinite flight. Which is a mobile passenger aircraft flight simulator mobile game which is taken very SERIOUSLY. you goof around and you get banned. They expect you to follow all proper procedures. So i'm not going to go into detail of my flight knowledge, because it's quite a bit.

**Describe the feature you'd like**
I would like an accessible way to achieve a pilots license, or maybe an application channel for one.

**Describe alternatives you've considered**
not really any I just said it above.

**Additional context**
nope

**Comment by Irovolve** [comment]
Umm.... you stole a plane then proceeded reverse around the whole airport while running over our squad cars...

**Comment by Irovolve** [comment]
Will be making a in-depth full suggestion about License's in general.
